config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "users/sign_up/customer", to: "users/registrations#new_customer", as: :new_customer_registration
  end

  get "dashboard" => "dashboard#index"

  resources :admin, only: [ :index ]
  resources :offers, only: [ :index ] do
    collection do
      post :bulk_create
    end
    member do
      patch :withdraw
      patch :accept
      patch :reject
    end
  end

  resources :deliveries, only: [ :index, :show ] do
    member do
      post :close
    end
    collection do
      get :load_truck
      get :start
    end
  end
  resources :companies, only: %i[show new create edit update]
  resources :shipment_statuses, only: %i[new create edit update destroy]
  resources :shipment_action_preferences, only: %i[edit update]

  resources :shipments do
    member do
      get :copy
      post :close
    end
    collection do
      post :assign_shipments_to_truck
      post :initiate_delivery
    end
  end
  resources :trucks, only: %i[show new create edit update destroy] do
    member do
      post :create_form
    end
  end
  resources :driver_managements, only: [ :new, :create, :edit, :update ] do
    member do
      post :reset_password
    end
  end

  resources :forms do
    get "show_modal", on: :member
  end

  resources :ratings, only: [ :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Uncomment to gain access to sidekiq web ui
  # mount Sidekiq::Web => '/sidekiq'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/views/admin/index.html.erb
<div class="page-header">
  <h1 class="page-title">Shipment Statuses</h1>
  <%= link_to 'New Shipment Status', new_shipment_status_path, class: 'button primary-button' %>
</div>

<table class="styled-table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="center-text">Locked for Customers?</th>
      <th class="center-text">Closed</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @shipment_statuses.each do |status| %>
    <tr>
      <td><%= status.name %></td>
      <td class="center-text">
        <% if status.locked_for_customers %>
        ✔️
        <% else %>
        ❌
        <% end %>
      </td>
      <td class="center-text">
        <% if status.closed %>
        ✔️
        <% else %>
        ❌
        <% end %>
      </td>
      <td>
        <%= link_to 'Edit', edit_shipment_status_path(status), class: 'action-link' %> |
        <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-link danger-link' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />

<div class="page-header">
  <h1 class="page-title">Manage Statuses Workflows</h1>
</div>

<table class="styled-table">
  <thead>
    <tr>
      <th>When...</th>
      <th class="center-text">Auto set the shipment status to....</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @preferences.each do |preference| %>
    <tr>
      <td><%= preference.action.gsub('_', ' ').capitalize %></td>
      <td class="center-text">
        <% if preference.shipment_status %>
        <%= preference.shipment_status.name %>
        <% else %>
        Don't update the status
        <% end %>
      </td>
      <td>
        <%= link_to 'Edit', edit_shipment_action_preference_path(preference), class: 'action-link' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />

<div class="page-header">
  <h1 class="page-title">Drivers</h1>
  <%= link_to "Create New Driver", new_driver_management_path, class: 'button primary-button' %>
</div>


<table class="styled-table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Driver's License</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @drivers.each do |driver| %>
    <tr>
      <td><%= driver.first_name %></td>
      <td><%= driver.last_name %></td>
      <td><%= driver.email %></td>
      <td><%= driver.drivers_license %></td>
      <td><%= driver.created_at.strftime("%Y-%m-%d") %></td>
      <td>
        <%= link_to 'Edit', edit_driver_management_path(driver), class: 'action-link' %> |
        <%= link_to 'Reset Password', reset_password_driver_management_path(driver), 
            class: 'action-link',
            method: :post,
            data: { confirm: 'Are you sure you want to reset the password?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />

<div class="page-header">
  <h1 class="page-title">Trucks</h1>
  <%= link_to 'New Truck', new_truck_path, class: 'button primary-button' %>
</div>

<div data-controller="create-maintenance">
  <div id="maintenance-modal" class="modal hidden">
    <%= render 'forms/maintenance_form'%>
  </div>
  <table class="styled-table">
    <thead>
      <tr>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Mileage</th>
        <th>License Plate</th>
        <th>Status</th>
        <th>Actions</th>
        <th>Maintenance</th>
      </tr>
    </thead>
    <tbody>
      <% @trucks.each do |truck| %>
      <tr>
        <td><%= truck.make %></td>
        <td><%= truck.model %></td>
        <td><%= truck.year %></td>
        <td><%= truck.mileage %></td>
        <td><%= truck.license_plate %></td>
        <td>
          <% if truck.active %>
          <span class="status-active">Active</span>
          <% else %>
          <span class="status-inactive">Maintenance Required</span>
          <% end %>
        </td>
        <td>
          <%= link_to 'Show', truck, class: 'action-link' %> |
          <%= link_to 'Edit', edit_truck_path(truck), class: 'action-link' %> |
          <%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-link danger-link' %>
        </td>
        <td>
          <% if !truck.active %>
          <button class="button warning-button" data-action="click->create-maintenance#open" data-modal-truck-id-value="<%= truck.id %>">
            Complete
          </button>
          <% else %>
          <span class="status-active">Up to Date</span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>