config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "users/sign_up/customer", to: "users/registrations#new_customer", as: :new_customer_registration
  end

  get "dashboard" => "dashboard#index"

  resources :admin, only: [ :index ]
  resources :offers, only: [ :index ] do
    collection do
      post :bulk_create
    end
    member do
      patch :withdraw
      patch :accept
      patch :reject
    end
  end

  resources :deliveries, only: [ :index, :show ] do
    member do
      post :close
    end
    collection do
      get :load_truck
      get :start
    end
  end
  resources :companies, only: %i[show new create edit update]
  resources :shipment_statuses, only: %i[new create edit update destroy]
  resources :shipment_action_preferences, only: %i[edit update]

  resources :shipments do
    member do
      get :copy
      post :close
    end
    collection do
      post :assign_shipments_to_truck
      post :initiate_delivery
    end
  end
  resources :trucks, only: %i[show new create edit update destroy] do
    member do
      post :create_form
    end
  end
  resources :driver_managements, only: [ :new, :create, :edit, :update ] do
    member do
      post :reset_password
    end
  end

  resources :forms do
    get "show_modal", on: :member
  end

  resources :ratings, only: [ :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Uncomment to gain access to sidekiq web ui
  # mount Sidekiq::Web => '/sidekiq'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :company, optional: true
  belongs_to :truck, optional: true
  belongs_to :shipment_status, optional: true

  has_many :delivery_shipments, dependent: :nullify
  has_many :deliveries, through: :delivery_shipments
  has_many :offers, dependent: :nullify

  validates :name, :sender_name, :sender_address, :receiver_name, :receiver_address, :weight, :length, :width, :height, presence: true
  validates :weight, :length, :width, :height, numericality: { greater_than: 0 }

  after_validation :geocode_sender, if: ->(obj) { obj.sender_address.present? && obj.sender_address_changed? }
  after_validation :geocode_receiver, if: ->(obj) { obj.receiver_address.present? && obj.receiver_address_changed? }

  scope :for_user, ->(user) { where(user_id: user.id) }

  scope :for_company, ->(company) { where(company_id: company.id) }

  scope :without_active_delivery, -> {
    where.not(
      id: joins(:deliveries)
          .merge(Delivery.active)
          .select(:id)
    )
  }

  def status
    shipment_status&.name
  end

  def claimed?
    !company.nil?
  end

  def open?
    !shipment_status&.closed
  end

  def active_delivery
    deliveries.active.first
  end

  def volume
    length * width * height
  end

  def latest_delivery_shipment
    delivery_shipments.order(created_at: :desc).first
  end

  def current_sender_address
    return sender_address if latest_delivery_shipment.nil?
    return latest_delivery_shipment.receiver_address if !latest_delivery_shipment.delivered_date.nil?
    latest_delivery_shipment.sender_address
  end

  def current_sender_latitude
    return sender_latitude if latest_delivery_shipment.nil?
    return latest_delivery_shipment.receiver_latitude if !latest_delivery_shipment.delivered_date.nil?
    latest_delivery_shipment.sender_latitude
  end

  def current_sender_longitude
    return sender_longitude if latest_delivery_shipment.nil?
    return latest_delivery_shipment.receiver_longitude if !latest_delivery_shipment.delivered_date.nil?
    latest_delivery_shipment.sender_longitude
  end

  def current_receiver_address
    latest_delivery_shipment.nil? ? receiver_address : latest_delivery_shipment.receiver_address
  end

  def current_receiver_latitude
    latest_delivery_shipment.nil? ? receiver_latitude : latest_delivery_shipment.receiver_latitude
  end

  def current_receiver_longitude
    latest_delivery_shipment.nil? ? receiver_longitude : latest_delivery_shipment.receiver_longitude
  end

  def has_active_offer_from?(company)
    offers.where(company: company, status: :issued).exists?
  end

  private

  def geocode_sender
    # Skip geocoding if coordinates were manually set
    return if sender_latitude_changed? || sender_longitude_changed?

    result = Geocoder.search(sender_address).first
    if result
      self.sender_latitude = result.latitude
      self.sender_longitude = result.longitude
    end
  end

  def geocode_receiver
    # Skip geocoding if coordinates were manually set
    return if receiver_latitude_changed? || receiver_longitude_changed?

    result = Geocoder.search(receiver_address).first
    if result
      self.receiver_latitude = result.latitude
      self.receiver_longitude = result.longitude
    end
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shipment, only: %i[ show edit update destroy copy close]

  # GET /shipments
  def index
    authorize Shipment
    @shipments = Shipment.where(user_id: current_user.id).order(deliver_by: :asc)
  end

  # GET /shipments/1
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
    authorize @shipment
  end

  # GET /shipments/1/edit
  def edit
    authorize @shipment
    @statuses = current_user.role == "customer" ? [] : ShipmentStatus.for_company(current_company)
  end

  # POST /shipments
  def create
    @shipment = Shipment.new(shipment_params)
    @shipment.user = current_user

    authorize @shipment
    if @shipment.save
      redirect_to @shipment, notice: "Shipment was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /shipments/1
  def update
    authorize @shipment

    service = UpdateShipment.new(@shipment, shipment_params, current_user)
    result = service.run

    if result.success?
      redirect_to @shipment, notice: result.message
    else
      redirect_to @shipment, alert: result.error
    end
  end

  # DELETE /shipments/1
  def destroy
    authorize @shipment
    @shipment.destroy!
    redirect_to shipments_path, status: :see_other, notice: "Shipment was successfully destroyed."
  end

  def copy
    @new_shipment = @shipment.dup
    @new_shipment.name = "Copy of #{@shipment.name}"
    @new_shipment.truck_id = nil
    @new_shipment.shipment_status_id = nil
    @new_shipment.company_id = nil
    @shipment = @new_shipment
    authorize @shipment
  end

  def close
    authorize Shipment
    unless @shipment.latest_delivery_shipment.delivery.in_progress?
      return redirect_to delivery_path(@shipment.active_delivery), alert: "Delivery is not in progress."
    end

    if @shipment.receiver_address != @shipment.latest_delivery_shipment.receiver_address
      @shipment.latest_delivery_shipment.update!(delivered_date: Time.now)
      @shipment.update!({
        company_id: nil,
        shipment_status_id: nil,
        truck_id: nil })
      ShipmentDeliveryMailer.partially_delivered_email(@shipment.id).deliver_later
      return redirect_to delivery_path(@shipment.active_delivery), alert: "Shipment successfully returned to shipment marketplace. Please remember to mark this delivery complete once all packages are delivered."
    end

    preference = current_company.shipment_action_preferences.find_by(action: "successfully_delivered")
    unless preference&.shipment_status_id
      return redirect_to delivery_path(@shipment.active_delivery), alert: "No preference set."
    end

    if preference.shipment_status_id == @shipment.shipment_status_id
      return redirect_to delivery_path(@shipment.active_delivery), alert: "Shipment is already closed."
    end

    @shipment.latest_delivery_shipment.update!(delivered_date: Time.now)
    @shipment.update!(shipment_status_id: preference.shipment_status_id)
    ShipmentDeliveryMailer.successfully_delivered_email(@shipment.id).deliver_later
    redirect_to delivery_path(@shipment.active_delivery), notice: "Shipment successfully closed."
  end

  def assign_shipments_to_truck
    authorize Shipment
    service = ScheduleDelivery.new(params, current_company)

    if service.run
      redirect_to load_truck_deliveries_path, notice: "Shipments successfully assigned to truck."
    else
      flash[:alert] = service.errors
      redirect_to load_truck_deliveries_path
    end
  end

  def initiate_delivery
    authorize Shipment
    if current_user.active_delivery.present?
      flash[:alert] = "Already on an active delivery"
      return redirect_to start_deliveries_path
    end

    service = InitiateDelivery.new(params, current_user, current_company)

    if service.run
      redirect_to service.delivery, notice: "Delivery was successfully created with #{service.delivery.shipments.count} shipments."
    else
      flash[:alert] = service.errors
      redirect_to start_deliveries_path
    end
  end

  private

    def set_shipment
      @shipment = Shipment.find(params[:id])

      if current_user.customer?
        if @shipment.user_id != current_user.id
          flash[:alert] = "You are not authorized to access this shipment."
          redirect_to shipments_path
        end
      else
        if @shipment.claimed? && @shipment.company_id != current_user.company_id
          flash[:alert] = "You are not authorized to access this shipment."
          redirect_to deliveries_path
        end
      end
    end

    def shipment_params
      if current_user.customer?
        params.require(:shipment).permit(
          :name,
          :sender_name,
          :sender_address,
          :receiver_name,
          :receiver_address,
          :weight,
          :length,
          :width,
          :height,
          :deliver_by)
      elsif current_user.admin?
        params.require(:shipment).permit(
          :shipment_status_id,
          :sender_address,
          :receiver_address,
          :weight,
          :length,
          :width,
          :height)
      elsif current_user.driver?
        params.require(:shipment).permit(
          :shipment_status_id,
          :weight,
          :length,
          :width,
          :height)
      else
        {}
      end
    end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
  def auto_select_sender(shipment)
    if current_user && current_user.role == "customer"
      current_user&.display_name
    else
      shipment.sender_name
    end
  end

  def auto_select_address(shipment)
    if current_user && current_user.role == "customer" && shipment.sender_address.blank?
      current_user&.home_address
    else
      shipment.sender_address
    end
  end

  def locked_fields?(shipment_status)
    return true if shipment_status&.closed
    return true if current_user && current_user.role == "customer" && shipment_status&.locked_for_customers
    false
  end

  def lock_fields_by_role(field)
    whitelisted_fields = {
      customer: %i[name sender_name sender_address receiver_name receiver_address weight length width height deliver_by],
      admin: %i[shipment_status_id sender_address receiver_address weight length width height],
      driver: %i[shipment_status_id weight length width height]
    }

    current_user_role = current_user.role.to_sym
    !whitelisted_fields.fetch(current_user_role, []).include?(field)
  end

  def back_link_path(user, shipment)
    return shipments_path if user.customer?
    return load_truck_deliveries_path if shipment.claimed? && shipment.truck_id.nil?
    return start_deliveries_path if shipment.claimed? && !shipment.truck_id.nil?

    deliveries_path
  end

  def prep_delivery_shipments_json(shipment)
    shipment.delivery_shipments.map do |delivery_shipment|
      {
        senderLat: delivery_shipment.sender_latitude,
        senderLng: delivery_shipment.sender_longitude,
        receiverLat: delivery_shipment.receiver_latitude,
        receiverLng: delivery_shipment.receiver_longitude,
        senderAddress: delivery_shipment.sender_address,
        receiverAddress: delivery_shipment.receiver_address
      }
    end.to_json
  end
end

app/views/shipments/_back_button.html.erb
<%= link_to 'Back to Index', back_link_path(current_user, shipment), class: 'button secondary-button' %>

app/views/shipments/_form.html.erb
<% disabled = locked_fields?(shipment.shipment_status) %>

<% if shipment.company %>
<div class="form-group">
  <p>Shipment has been claimed by <%= shipment.company.name %>.
    <% if disabled %>
    No further updates are allowed.
    <% end %>
  </p>
</div>
<% end %>

<%= form_with(model: shipment, local: true, class: 'styled-form') do |form| %>
<% if shipment.errors.any? %>
<div class="error-messages">
  <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>
  <ul>
    <% shipment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<% unless statuses.empty? %>
<div class="form-group">
  <%= form.label :shipment_status_id, "Shipment Status", class: 'form-label' %>
  <%= form.select :shipment_status_id, 
                      options_from_collection_for_select(statuses, :id, :name, shipment.shipment_status_id), 
                      { include_blank: "Select a Status" }, 
                      { class: 'form-input', disabled: disabled || lock_fields_by_role(:shipment_status_id) } %>
</div>
<% end %>

<div class="form-group">
  <%= form.label :name, class: 'form-label' %>
  <%= form.text_field :name, class: 'form-input', disabled: disabled || lock_fields_by_role(:name)%>
</div>

<div class="form-group">
  <%= form.label :sender_name, class: 'form-label' %>
  <%= form.text_field :sender_name, class: 'form-input', value: auto_select_sender(shipment), disabled: disabled || lock_fields_by_role(:sender_name) %>
</div>

<div class="form-group">
  <%= form.label :sender_address, class: 'form-label' %>
  <%= form.text_area :sender_address, class: 'form-input', value: auto_select_address(shipment), disabled: disabled || lock_fields_by_role(:sender_address) %>
</div>

<div class="form-group">
  <%= form.label :receiver_name, class: 'form-label' %>
  <%= form.text_field :receiver_name, class: 'form-input', disabled: disabled || lock_fields_by_role(:receiver_name) %>
</div>

<div class="form-group">
  <%= form.label :receiver_address, class: 'form-label' %>
  <%= form.text_area :receiver_address, class: 'form-input', disabled: disabled || lock_fields_by_role(:receiver_address) %>
</div>

<div class="form-group">
  <%= form.label :weight, "Weight (kg)", class: 'form-label' %>
  <%= form.text_field :weight, class: 'form-input', disabled: disabled || lock_fields_by_role(:weight) %>
</div>

<div class="form-group">
  <%= form.label :length, "Length (cm)", class: 'form-label' %>
  <%= form.text_field :length, class: 'form-input', disabled: disabled || lock_fields_by_role(:length) %>
</div>

<div class="form-group">
  <%= form.label :width, "Width (cm)", class: 'form-label' %>
  <%= form.text_field :width, class: 'form-input', disabled: disabled || lock_fields_by_role(:width) %>
</div>

<div class="form-group">
  <%= form.label :height, "Height (cm)", class: 'form-label' %>
  <%= form.text_field :height, class: 'form-input', disabled: disabled || lock_fields_by_role(:height) %>
</div>

<div class="form-group">
  <%= form.label :deliver_by, "Deliver By", class: 'form-label' %>
  <%= form.date_field :deliver_by, class: 'form-input', disabled: disabled || lock_fields_by_role(:deliver_by) %>
</div>

<div class="form-actions">
  <%= form.submit 'Save Shipment', class: 'button primary-button', disabled: disabled %>
</div>
<% end %>

app/views/shipments/copy.html.erb
<div class="page-header">
  <h1 class="page-title">Copy Shipment</h1>
  <%= render 'back_button', shipment: @shipment%>
</div>

<div class="form-container">
  <%= render 'form', shipment: @shipment, statuses: @statuses || [] %>
</div>

app/views/shipments/edit.html.erb
<div class="page-header">
  <h1 class="page-title">Edit Shipment</h1>
  <%= render 'back_button', shipment: @shipment%>
</div>

<div class="form-container">
  <%= render 'form', shipment: @shipment, statuses: @statuses || [] %>
</div>

app/views/shipments/index.html.erb
<div class="page-header">
  <h1 class="page-title">Shipments</h1>
  <%= link_to 'New Shipment', new_shipment_path, class: 'button primary-button' %>
</div>

<table class="styled-table">
  <thead>
    <tr>
      <th>Company</th>
      <th>Status</th>
      <th>Name</th>
      <th>Reciever Name</th>
      <th>Receiver Address</th>
      <th>Deliver By</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @shipments.each do |shipment| %>
    <tr>
      <td><%= shipment&.company&.name %></td>
      <td><%= shipment.status %></td>
      <td><%= shipment.name %></td>
      <td><%= shipment.receiver_name %></td>
      <td><%= shipment.receiver_address %></td>
      <td><%= shipment.deliver_by %></td>
      <td>
        <%= link_to 'Show', shipment, class: 'action-link' %> |
        <%= link_to 'Edit', edit_shipment_path(shipment), class: 'action-link' %> |
        <%= link_to 'Copy', copy_shipment_path(shipment), class: 'action-link' %>
        <% unless shipment.claimed? %>
        | <%= link_to 'Destroy', shipment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-link danger-link' %>
        <% end %>

      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shipments/new.html.erb
<div class="page-header">
  <h1 class="page-title">New Shipment</h1>
  <%= render 'back_button', shipment: @shipment%>
</div>

<div class="form-container">
  <%= render 'form', shipment: @shipment, statuses: @statuses || [] %>
</div>

app/views/shipments/show.html.erb
<div class="page-header">
  <h1 class="page-title">Shipment Details</h1>
  <%= render 'back_button', shipment: @shipment%>
</div>

<%= tag.div id: "shipment-map",
            data: {
              controller: "show-shipment-map",
              show_shipment_map_sender_lat_value: @shipment.sender_latitude,
              show_shipment_map_sender_lng_value: @shipment.sender_longitude,
              show_shipment_map_receiver_lat_value: @shipment.receiver_latitude,
              show_shipment_map_receiver_lng_value: @shipment.receiver_longitude,
              show_shipment_map_sender_address_value: @shipment.sender_address,
              show_shipment_map_receiver_address_value: @shipment.receiver_address,
              show_shipment_map_additional_coordinates_value: prep_delivery_shipments_json(@shipment)
            },
            style: "height: 500px; width: 100%;" %>

<br />

<div class="details-container">
  <p><strong>Name:</strong> <span class="detail-value"><%= @shipment.name %></span></p>
  <p><strong>Status: </strong>
    <span class="detail-value"><%= @shipment.shipment_status_id ? @shipment.status : "No Current Status"%></span>
  </p>
  <p><strong>Sender Name:</strong> <span class="detail-value"><%= @shipment.sender_name %></span></p>
  <p><strong>Sender Address:</strong> <span class="detail-value"><%= @shipment.sender_address %></span></p>
  <p><strong>Receiver Name:</strong> <span class="detail-value"><%= @shipment.receiver_name %></span></p>
  <p><strong>Receiver Address:</strong> <span class="detail-value"><%= @shipment.receiver_address %></span></p>
  <p><strong>Weight:</strong> <span class="detail-value"><%= @shipment.weight %> kg</span></p>
  <p><strong>Length:</strong> <span class="detail-value"><%= @shipment.length %> cm</span></p>
  <p><strong>Width:</strong> <span class="detail-value"><%= @shipment.width %> cm</span></p>
  <p><strong>Height:</strong> <span class="detail-value"><%= @shipment.height %> cm</span></p>
  <p><strong>Delivery By:</strong> <span class="detail-value"><%= @shipment.deliver_by %></span></p>
  <% if @shipment.truck && !@current_user.customer? %>
  <p><strong>Truck:</strong> <span class="detail-value"><%= link_to @shipment.truck.display_name, @shipment.truck %></span></p>
  <% end %>
</div>

<div class="details-actions">
  <%= link_to 'Edit Shipment', edit_shipment_path(@shipment), class: 'button primary-button' %>
  <% if @current_user.customer? %>
  <%= link_to 'Copy Shipment', copy_shipment_path(@shipment), class: 'button warning-button' %>
  <% unless @shipment.claimed? %>
  <%= link_to 'Destroy Shipment', @shipment, method: :delete, class: 'button danger-button', data: { confirm: 'Are you sure?' } %>
  <% end %>
  <% end %>

</div>

<div data-controller="rating-modal">
  <!-- Rating Modal -->
  <div data-rating-modal-target="modal" class="modal">
    <%= render 'ratings/form' %>
  </div>

  <table class="styled-table">
    <thead>
      <tr>
        <th>Company</th>
        <th>Departed From</th>
        <th>Arriving At</th>
        <th>Processing Date</th>
        <th>Delivered Date</th>
        <th>Rating</th>
      </tr>
    </thead>
    <tbody>
      <% @shipment.delivery_shipments.order(created_at: :desc).each do |del_ship| %>
      <tr>
        <td>
          <% company = @shipment.company || del_ship.delivery&.user&.company %>
          <% if company.present? %>
          <%= link_to company.name, company_path(company), class: "company-link" %>
          <% if company.phone_number.present? %>
          <span style="cursor: help;" title="Phone: <%= company.phone_number %>">
            &#9432;
          </span>
          <% end %>
          <% else %>
          N/A
          <% end %>
        </td>
        <td><%= del_ship.sender_address %></td>
        <td><%= del_ship.receiver_address %></td>
        <td><%= del_ship.loaded_date&.strftime("%Y-%m-%d") %></td>
        <td><%= del_ship.delivered_date&.strftime("%Y-%m-%d") %></td>
        <td>
          <% if del_ship.delivered_date.present? %>
          <% existing_rating = del_ship.rating %>
          <% if existing_rating.present? %>
          <%= star_rating(existing_rating.stars, size: "1.2em") %>
          <% if existing_rating.comment.present? %>
          <br><small><%= existing_rating.comment %></small>
          <% end %>
          <% else %>
          <% company = @shipment.company || del_ship.delivery&.user&.company %>
          <% if company.present? && @current_user.customer? %>
          <button class="button primary-button small-button" data-action="rating-modal#showModal" data-delivery-shipment-id="<%= del_ship.id %>" data-company-id="<%= company.id %>">
            Rate
          </button>
          <% end %>
          <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>